/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Author: re1monsen (https://sketchfab.com/re1monsen)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/space-station-0da4a24e7edd49159737675ffcc06228
Title: Space Station
*/

import * as THREE from "three";
import type { ThreeElements } from "@react-three/fiber";
import { useGLTF } from "@react-three/drei";
import type { GLTF } from "three-stdlib";

type GLTFResult = GLTF & {
  nodes: Record<string, THREE.Mesh>;
  materials: {
    Main: THREE.MeshStandardMaterial;
    emitrED: THREE.MeshStandardMaterial;
  };
};

export function SpaceStationModel(props: ThreeElements["group"]) {
  const { nodes, materials } = useGLTF("/space_station/scene.gltf") as unknown as GLTFResult;
  return (
    <group {...props} dispose={null}>
      <group rotation={[-1.446, -0.1, -0.003]} scale={1.191}>
        <group rotation={[Math.PI / 2, 0, 0]} scale={0.01}>
          <mesh castShadow receiveShadow geometry={nodes.spacestation001_low_Main_0.geometry} material={materials.Main} rotation={[-Math.PI / 2, 0, 0]} scale={100} />
          <mesh castShadow receiveShadow geometry={nodes.spacestation002_low_Main_0.geometry} material={materials.Main} rotation={[-Math.PI / 2, 0, 0]} scale={100} />
          <mesh castShadow receiveShadow geometry={nodes.spacestation003_low_Main_0.geometry} material={materials.Main} rotation={[-Math.PI / 2, 0, 0]} scale={100} />
          <mesh castShadow receiveShadow geometry={nodes.spacestation004_low_Main_0.geometry} material={materials.Main} rotation={[-Math.PI / 2, 0, 0]} scale={100} />
          <mesh castShadow receiveShadow geometry={nodes.spacestation005_low_Main_0.geometry} material={materials.Main} rotation={[-Math.PI / 2, 0, 0]} scale={100} />
          <mesh castShadow receiveShadow geometry={nodes.spacestation006_low_Main_0.geometry} material={materials.Main} rotation={[-Math.PI / 2, 0, 0]} scale={100} />
          <mesh castShadow receiveShadow geometry={nodes.spacestation007_low_Main_0.geometry} material={materials.Main} rotation={[-Math.PI / 2, 0, 0]} scale={100} />
          <mesh castShadow receiveShadow geometry={nodes.spacestation008_low_Main_0.geometry} material={materials.Main} rotation={[-Math.PI / 2, 0, 0]} scale={100} />
          <mesh castShadow receiveShadow geometry={nodes.spacestation009_low_Main_0.geometry} material={materials.Main} rotation={[-Math.PI / 2, 0, 0]} scale={100} />
          <mesh castShadow receiveShadow geometry={nodes.spacestation010_low_Main_0.geometry} material={materials.Main} rotation={[-Math.PI / 2, 0, 0]} scale={100} />
          <mesh castShadow receiveShadow geometry={nodes.spacestation011_low_Main_0.geometry} material={materials.Main} rotation={[-Math.PI / 2, 0, 0]} scale={100} />
          <mesh castShadow receiveShadow geometry={nodes.spacestation012_low_Main_0.geometry} material={materials.Main} rotation={[-Math.PI / 2, 0, 0]} scale={100} />
          <mesh castShadow receiveShadow geometry={nodes.spacestation013_low_Main_0.geometry} material={materials.Main} rotation={[-Math.PI / 2, 0, 0]} scale={100} />
          <mesh castShadow receiveShadow geometry={nodes.spacestation014_low_Main_0.geometry} material={materials.Main} rotation={[-Math.PI / 2, 0, 0]} scale={100} />
          <mesh castShadow receiveShadow geometry={nodes.spacestation015_low_Main_0.geometry} material={materials.Main} rotation={[-Math.PI / 2, 0, 0]} scale={100} />
          <mesh castShadow receiveShadow geometry={nodes.spacestation016_low_Main_0.geometry} material={materials.Main} rotation={[-Math.PI / 2, 0, 0]} scale={100} />
          <mesh castShadow receiveShadow geometry={nodes.spacestation017_low_Main_0.geometry} material={materials.Main} rotation={[-Math.PI / 2, 0, 0]} scale={100} />
          <mesh castShadow receiveShadow geometry={nodes.spacestation018_low_Main_0.geometry} material={materials.Main} rotation={[-Math.PI / 2, 0, 0]} scale={100} />
          <mesh castShadow receiveShadow geometry={nodes.spacestation019_low_Main_0.geometry} material={materials.Main} rotation={[-Math.PI / 2, 0, 0]} scale={100} />
          <mesh castShadow receiveShadow geometry={nodes.spacestation020_low_Main_0.geometry} material={materials.Main} rotation={[-Math.PI / 2, 0, 0]} scale={100} />
          <mesh castShadow receiveShadow geometry={nodes.spacestation021_low_Main_0.geometry} material={materials.Main} rotation={[-Math.PI / 2, 0, 0]} scale={100} />
          <mesh castShadow receiveShadow geometry={nodes.spacestation022_low_Main_0.geometry} material={materials.Main} rotation={[-Math.PI / 2, 0, 0]} scale={100} />
          <mesh castShadow receiveShadow geometry={nodes.spacestation023_low_Main_0.geometry} material={materials.Main} rotation={[-Math.PI / 2, 0, 0]} scale={100} />
          <mesh castShadow receiveShadow geometry={nodes.spacestation024_low_Main_0.geometry} material={materials.Main} rotation={[-Math.PI / 2, 0, 0]} scale={100} />
          <mesh castShadow receiveShadow geometry={nodes.spacestation025_low_Main_0.geometry} material={materials.Main} rotation={[-Math.PI / 2, 0, 0]} scale={100} />
          <mesh castShadow receiveShadow geometry={nodes.spacestation026_low_Main_0.geometry} material={materials.Main} position={[-658.787, -427.535, -105.87]} rotation={[-1.555, -0.003, 1.343]} scale={100} />
          <mesh castShadow receiveShadow geometry={nodes.spacestation027_low_Main_0.geometry} material={materials.Main} position={[334.658, -47.48, -855.527]} rotation={[-Math.PI / 2, 0, -1.774]} scale={100} />
          <mesh castShadow receiveShadow geometry={nodes.spacestation029_low_Main_0.geometry} material={materials.Main} rotation={[-Math.PI / 2, 0, 0]} scale={100} />
          <mesh castShadow receiveShadow geometry={nodes.spacestation030_low_Main_0.geometry} material={materials.Main} rotation={[-Math.PI / 2, 0, 0]} scale={100} />
          <mesh castShadow receiveShadow geometry={nodes.spacestation031_low_Main_0.geometry} material={materials.Main} rotation={[-Math.PI / 2, 0, 0]} scale={100} />
          <mesh castShadow receiveShadow geometry={nodes.spacestation032_low_Main_0.geometry} material={materials.Main} rotation={[-Math.PI / 2, 0, 0]} scale={100} />
          <mesh castShadow receiveShadow geometry={nodes.spacestation033_low_Main_0.geometry} material={materials.Main} rotation={[-Math.PI / 2, 0, 0]} scale={100} />
          <mesh castShadow receiveShadow geometry={nodes.spacestation034_low_Main_0.geometry} material={materials.Main} rotation={[-Math.PI / 2, 0, 0]} scale={100} />
          <mesh castShadow receiveShadow geometry={nodes.spacestation_low_Main_0.geometry} material={materials.Main} rotation={[-Math.PI / 2, 0, 0]} scale={100} />
          <mesh castShadow receiveShadow geometry={nodes.emit_low001_emitrED_0.geometry} material={materials.emitrED} position={[-658.787, -427.535, -105.87]} rotation={[-1.555, -0.003, 1.343]} scale={100} />
          <mesh castShadow receiveShadow geometry={nodes.emit_low_emitrED_0.geometry} material={materials.emitrED} position={[334.658, -47.48, -855.527]} rotation={[-Math.PI / 2, 0, -1.774]} scale={100} />
          <mesh castShadow receiveShadow geometry={nodes.emit_low002_emitrED_0.geometry} material={materials.emitrED} rotation={[-Math.PI / 2, 0, 0]} scale={100} />
        </group>
      </group>
    </group>
  );
}

useGLTF.preload("/space_station/scene.gltf");
